/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class DirectoryWatcher {
  static new(callback: (...args: any[]) => any): DirectoryWatcher
  watch(path: string): void
  unwatch(path: string): boolean
  getWatchedPaths(): Array<string>
}
